version: '3'
services:
  web:
    build:
      context: .
      args:
        - GITHUB_TOKEN=${GITHUB_TOKEN}
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - /app/node_modules
    command: [ "npm", "run", "dev" ]
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN}
